### ISSUE TITLE
Git basics to be completed

### ISSUE THREAD

**Issue by JordanMCode** [JordanMCode/Treehouse#2]
## TODO

*Courses left to complete the Treehouse Git basics track*

* [ ] Working by yourself
* [ ] Working on a team
* [ ] Create a Web prescence on Github
* [ ] Get involved in Open Source

🎉  👌  🎊
